name: freebsd

on:
  push:
    paths:
      - yasio/**/*
      - thirdparty/**/*
      - tests/**/*
      - examples/**/*
      - CMakeLists.txt
      - .github/workflows/freebsd-ci.yml
      - ci/**/*
      - extensions/**/*

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  TRAVIS_OS_NAME: freebsd
  BUILD_TARGET: freebsd
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'TRAVIS_OS_NAME BUILD_TARGET'
        usesh: true
        prepare: |
          pkg install -y cmake
          pkg install -y python3
          pkg search perl5
          # pkg install -y perl5.34-5.34.0
          pkg_add -v -r perl
          perl --version
        run: |
          echo Building on freebsd...
          cmake -G "Unix Makefiles" -S . -Bbuild
          cmake --build build
