name: ios

on:
  push:
    paths:
      - yasio/**/*
      - thirdparty/**/*
      - tests/**/*
      - examples/**/*
      - CMakeLists.txt
      - .github/workflows/ios-ci.yml
      - ci/**/*
      - extensions/**/*

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest
    
    strategy:
      matrix:
        target:
          - ios
          - tvos
          - watchos
    env:
      BUILD_TARGET: ${{ matrix.target }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      shell: pwsh
      run: ./build.ps1 -p $env:BUILD_TARGET -a arm64
