name: osx

on:
  push:
    paths:
      - yasio/**/*
      - thirdparty/**/*
      - tests/**/*
      - examples/**/*
      - CMakeLists.txt
      - .github/workflows/osx-ci.yml
      - ci/**/*
      - extensions/**/*

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TARGET: osx
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all
      run: ci/install.sh
      
    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: ci/build.sh
