name: pull_request

on: [pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  GITHUB_CI: 'true'
  BUILD_TYPE: Release

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x86
          - x64
    env:
      BUILD_ARCH: ${{ matrix.arch }}
      TOOLCHAIN: 'msvc'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ilammy/msvc-dev-cmd@v1.9.0
        with: 
          arch: ${{ env.BUILD_ARCH }}
      - name: Build
        run: ci\build.ps1
  build-mingw:
    name: build-mingw
    runs-on: windows-latest
    strategy:
      matrix:
        include:
        - { sys: mingw64, env: x86_64 }
        - { sys: mingw32, env: i686 }
    env:
      TOOLCHAIN: 'mingw'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: msys2/setup-msys2@v2
        with: 
          msystem: ${{ matrix.sys }}
          install: mingw-w64-${{ matrix.env }}-toolchain
      - name: Build
        run: ci\build.ps1
  build-linux:
    name: build-linux
    runs-on: ubuntu-18.04
    env:
      TRAVIS_OS_NAME: linux
      BUILD_TARGET: linux
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          ci/install.sh
          ci/build.sh
  build-android:
    name: build-android
    runs-on: ubuntu-18.04
    env:
      TRAVIS_OS_NAME: linux
      BUILD_TARGET: android
      PYENV_VERSION: 2.7.18
      NDK_VER: r16b
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          ci/install.sh
          ci/build.sh
  build-osx:
    name: build-osx
    runs-on: macos-latest
    env:
      TRAVIS_OS_NAME: osx
      BUILD_TARGET: osx
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          ci/install.sh
          ci/build.sh
  build-ios:
    name: build-ios
    runs-on: macos-latest
    env:
      TRAVIS_OS_NAME: osx
      BUILD_TARGET: ios
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          ci/install.sh
          ci/build.sh
  build-freebsd:
    name: build-freebsd
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        uses: vmactions/freebsd-vm@v0.1.0
        with:
          prepare: pkg install -y cmake
          run: |
            echo Building on freebsd...
            cmake -G "Unix Makefiles" -S . -Bbuild
            cmake --build build
