name: pull_request

on: [pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PING_HOST: github.com

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x86
          - x64
    env:
      BUILD_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: ilammy/msvc-dev-cmd@v1.12.0
        with: 
          arch: ${{ env.BUILD_ARCH }}
      - name: Build
        run: ci\build.ps1 -p win -a $env:BUILD_ARCH
  build-mingw:
    name: build-mingw
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: msys2/setup-msys2@v2
        with: 
          msystem: mingw64
          install: mingw-w64-x86_64-toolchain
      - name: Build
        run: ci\build.ps1 -p win -cc 'mingw-gcc'
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    env:
      BUILD_TARGET: linux
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        shell: pwsh
        run: ./ci/build.ps1 -p linux
  build-android:
    name: build-android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm
          - arm64
          - x86
          - x64
    env:
      BUILD_ARCH: ${{ matrix.arch }}
      # r16b can't runs on latest ubuntu, test works on ubuntu-18.04
      NDK_VER: r19c
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        shell: pwsh
        run: ./ci/build.ps1 -p android -a $env:BUILD_ARCH
  build-osx:
    name: build-osx
    runs-on: macos-latest
    env:
      BUILD_TARGET: osx
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        shell: pwsh
        run: ./ci/build.ps1 -p osx -a x64
  build-ios:
    name: build-ios
    runs-on: macos-latest
    env:
      BUILD_TARGET: ios
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        shell: pwsh
        run: ./ci/build.ps1 -p ios -a arm64
  build-freebsd:
    name: build-freebsd
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        uses: vmactions/freebsd-vm@main
        with:
          usesh: true
          prepare: |
            pkg install -y cmake
            pkg install -y python3
            # required by mbedtls-3.3.0
            pkg install -y py39-pip
            pip install jsonschema jinja2
            # install perl5, localtion: /usr/local/bin
            pkg search perl5
            pkg search perl5 | cut -d' ' -f1 | head -n 1 | xargs pkg install -y
            perl -v
          run: |
            echo Building on freebsd...
            cmake -G "Unix Makefiles" -S . -Bbuild -DYASIO_SSL_BACKEND=2
            cmake --build build
            echo run test icmp on freebsd...
            ./build/tests/icmp/icmptest
