name: pull_request

on: [pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PING_HOST: www.microsoft.com

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x86
          - x64
    env:
      BUILD_ARCH: ${{ matrix.arch }}
      TOOLCHAIN: 'msvc'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: ilammy/msvc-dev-cmd@v1.12.0
        with: 
          arch: ${{ env.BUILD_ARCH }}
      - name: Build
        run: ci\build.ps1
  build-mingw:
    name: build-mingw
    runs-on: windows-latest
    strategy:
      matrix:
        include:
        - { sys: mingw64, env: x86_64 }
        - { sys: mingw32, env: i686 }
    env:
      TOOLCHAIN: 'mingw'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: msys2/setup-msys2@v2
        with: 
          msystem: ${{ matrix.sys }}
          install: mingw-w64-${{ matrix.env }}-toolchain
      - name: Build
        run: ci\build.ps1
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    env:
      BUILD_TARGET: linux
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          ci/install.sh
          ci/build.sh
  build-android:
    name: build-android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
    env:
      BUILD_ARCH: ${{ matrix.arch }}
      BUILD_TARGET: android
      # r16b can't runs on latest ubuntu, test works on ubuntu-18.04
      NDK_VER: r19c
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          ci/install.sh
          ci/build.sh
  build-osx:
    name: build-osx
    runs-on: macos-latest
    env:
      BUILD_TARGET: osx
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          ci/install.sh
          ci/build.sh
  build-ios:
    name: build-ios
    runs-on: macos-latest
    env:
      BUILD_TARGET: ios
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          ci/install.sh
          ci/build.sh
  build-freebsd:
    name: build-freebsd
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        uses: vmactions/freebsd-vm@main
        with:
          usesh: true
          prepare: |
            pkg install -y cmake
            pkg install -y python3
            # required by mbedtls-3.3.0
            pkg install -y py39-pip
            pip install jsonschema jinja2
            # install perl5.34.x, localtion: /usr/local/bin
            set perl_pkg_name=`pkg search perl5 | cut -d' ' -f1`
            pkg install -y $perl_pkg_name
          run: |
            echo Building on freebsd...
            cmake -G "Unix Makefiles" -S . -Bbuild
            cmake --build build
            echo run test icmp on freebsd...
            ./build/tests/icmp/icmptest
