name: windows

on:
  push:
    paths:
      - yasio/**/*
      - thirdparty/**/*
      - tests/**/*
      - examples/**/*
      - CMakeLists.txt
      - .github/workflows/windows-ci.yml
      - ci/**/*
      - extensions/**/*

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  TOOLCHAIN: 'msvc'
  PING_HOST: github.com

jobs:
  msvc:
    if: ${{ !startsWith(github.event.commits[0].message, 'Merge pull request') }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x86
          - x64
    env:
      BUILD_ARCH: ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: ilammy/msvc-dev-cmd@v1.12.0
      with: 
        arch: ${{ env.BUILD_ARCH }}
        uwp: 'false'

    - name: Build
      run: ci\build.ps1 -p win -a $env:BUILD_ARCH
  clang:
    if: ${{ !startsWith(github.event.commits[0].message, 'Merge pull request') }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: ilammy/msvc-dev-cmd@v1.12.0
      with: 
        arch: ${{ env.BUILD_ARCH }}
        uwp: 'false'

    - name: Build
      run: ci\build.ps1 -p win -cc clang
  uwp:
    if: ${{ !startsWith(github.event.commits[0].message, 'Merge pull request') }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x86
          - x64
    env:
      BUILD_ARCH: ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: ilammy/msvc-dev-cmd@v1.12.0
      with: 
        arch: ${{ env.BUILD_ARCH }}
        uwp: 'true'

    - name: Build
      run: ci\build.ps1 -p uwp -a $env:BUILD_ARCH
